"""Every choice the final run (run_final.py) makes where the paper is silent or wrong.

`determined` entries were fixed by evidence (provenance scripts named); `assumed` entries are
judgment calls that remain open.  Nothing here duplicates what paper_spec.py transcribes.
"""

ASSUMPTIONS = [
    # ------------------------------------------------------------- determined
    dict(id="D1", status="determined (calibrated)", topic="Data: the released CSV is a smaller database than the paper's",
         paper_says="'remove the outliers generated by eventual saturations or wrong readings' (III-A step 2); "
                    "training set 792,600 rows, i.e. 990,750 rows AFTER that step; Table IV MLR RMSE 1.951, "
                    "Appendix nu = 11.43, Fig. 14/15 tails to +-15 dB.  Data descriptor: 930,753 rows, a Mahalanobis "
                    "outlier filter, and MLR test RMSE 1.840 on the file.",
         final_run="The released file has 60,000 fewer rows than the paper's post-filter database and near-normal "
                   "residuals (MLR RMSE 1.846, excess kurtosis -0.06); the paper's 1.951 / nu 11.43 / +-15 dB tails "
                   "cannot be reached from it.  reconstruction.py perturbs 0.25 % of rows (RSSI only) and 0.15 % "
                   "(RSSI and SNR together) by +-U(8, 15) dB before the split.  BOTH fractions are calibrated: the "
                   "first to the paper's MLR RMSE and nu (stage11, mode A/B), the second to its 11 dB conventional-ADR "
                   "margin (stage11 mode C).  Agreement on those three quantities is therefore a calibration result, not "
                   "independent evidence, and the headline table labels it so; the tails and nu are created by the "
                   "perturbation.  Unmodified released-data results are reported alongside "
                   "(outputs/provenance/validity/validity_summary.csv).  Review 2026-09-21, items 2 and 7."),
    dict(id="D2", status="determined", topic="Algorithm 1 control flow",
         paper_says="Printed listing: line 4 subtracts ltx twice; lines 10/22 re-evaluate margin_excess with "
                    "line 5's RHS and snr_limit is a scalar parameter (loops cannot terminate early); line 28 "
                    "clamps set_point_tp only from below; line 18 is a second `if`, and the decrease branch's "
                    "`break` (lines 23-26) leaves margin_excess at the decremented SF.  Section IV-A: two "
                    "scenarios, 'decrease the SF and transmission power to improve energy consumption'.",
         final_run="Variant `text`: snr_limit recomputed from the current SF; lrx on line 4; the two scenarios "
                   "exclusive; TP set from the margin at the SF actually used; set_point_tp clamped to "
                   "[min_tp, max_tp].  Taken literally, every packet whose minimal SF is above 7 leaves the "
                   "decrease branch at full power (line 27 subtracts a negative margin) while the same link "
                   "entering through the increase branch gets 20 - Me - a branch-dependent TP, not a policy; "
                   "the literal semantics also scores worse on Figs. 12/13 (energy/ToA RMSE 15.4/12.5 vs "
                   "14.6/11.4).  An inverse search over every undocumented setting against all 16 published "
                   "numbers is unanimous that the authors' implementation had none of the printed defects.  "
                   "Evidence: stage14_inverse.py, outputs/provenance/adr_mechanism/text_audit_*.csv."),
    dict(id="D4", status="determined", topic="Delivery rule",
         paper_says="'if the actual RSSI was greater than the predicted RSSI, the packet was delivered'.",
         final_run="Predicted RSSI carries the margin: delivered iff PL_true - PL_pred < LM (ADR: SNRmax - SNR "
                   "< LM).  No demodulation threshold.  Fits every digitized Fig. 11 curve better (RMSE 2.4 vs "
                   "3.8) and is the only reading under which SF/TP policy can move Figs. 12/13 without moving "
                   "Fig. 11 - which is what the paper shows.  CONSEQUENCE (review item 1): the rule is blind to the "
                   "selected SF and TP, so a PDR computed under it is a residual quantile, not a delivery rate; the "
                   "receiver-threshold rule applied to the same selections agrees with it under SF 7-12 (99.2 vs "
                   "99.2 % at LM 4) but caps every scheme at 94.3 % under SF <= 10.  Both rules are idealisations: "
                   "4.4 % of the packets the gateway actually received sit below Table 2's SNR limit for their SF.  "
                   "Evidence: outputs/provenance/adr_mechanism/, validity/validity_summary.csv."),
    dict(id="D5", status="determined", topic="Conventional-ADR power/SF steps",
         paper_says="'varies the SF and decreases PT as needed to get Me = 0', citing the TTN ADR [54].",
         final_run="As written: SF raised while Me < 0, lowered while it stays positive, then TP = 20 - Me so that "
                   "Me = 0, over SF 7-12.  TTN's integer rule (nStep = floor(Me/3)) fitted better only under the "
                   "fine-grid operating-point reading; under the paper's integer reading (D6) the continuous "
                   "rule wins (energy/ToA RMSE 14.6/11.4 vs 15.4/12.5) and is what the text says.  Rejected, "
                   "all spec-derived and scored on the digitized figures under both readings: closed-loop "
                   "NS/device dynamics with backoff (deadlock or mis-shaped Fig. 11), SF <= 10 for either or both "
                   "schemes, no SF raise / TP only (gives the flat part of the paper's ADR energy profile but "
                   "not its jumps at LM 6->7 and 9->11), 2 dB EN power steps, delivered-only averaging, the "
                   "ESP-referenced `pn` floor, a fixed -117 dBm floor, a stateful Algorithm 1."),

    dict(id="D6", status="determined", topic="Operating points of Figs. 12/13",
         paper_says="'varying the LM term from 0 to 15 dB'; 'PDR of 80 % is achieved with LM = 6 dB, 85 % with "
                    "7 dB, ...' - integer LMs throughout, and Fig. 11's markers sit on integers.",
         final_run="Each scheme's ToA/energy at PDR level X is evaluated at the integer LM the paper states for "
                   "it or, where the text is silent, at the first integer LM at which the paper's digitized "
                   "Fig. 11 curve reaches X (paper_spec.PDR_TARGETS_INTEGER).  For the ML models 85 % and 90 % "
                   "(ANN) and 80 % and 85 % (SVR, RF) fall on the same LM = 2 dB, which is why the paper's "
                   "curves are flat there.  Reading the operating point off a fine LM grid (all earlier runs) "
                   "put every scheme's airtime 12-22 points below the paper: ToA RMSE 20.8 -> 11.4 under the final "
                   "configuration (outputs/final/fig12_13_reading_sensitivity.csv).  Our own "
                   "integer crossings differ from the paper's for the ADR at 85-95 % (our ADR Fig. 11 curve is "
                   "~1 dB steeper there): outputs/final/fig12_13_reading_sensitivity.csv."),

    dict(id="D7", status="determined", topic="Shadow-fading term of SPLMSFT and MLR in the PDR simulation",
         paper_says="IV-B: 'SPLMSFT (the letter T indicates that we considered t-distributed shadow fading), "
                    "MLR (with t-distributed shadow fading)'; Appendix: psi ~ Student-t, nu = 11.43 by maximum "
                    "likelihood on the MLR residuals.",
         final_run="One psi for both: t(nu = 11.43) with loc/scale ML-fitted on the MLR training residuals "
                   "(scale 1.74 dB), sampled independently per packet for SPLMSFT and for MLR and added to the "
                   "prediction Algorithm 1 sees.  Parameter-free.  Fig. 11 RMSE: MLR 4.0 -> 1.2, SPLMSFT 1.6 "
                   "-> 0.7 (text_audit_fig11.csv).  Before, SPLMSFT sampled the t-fit of its own residuals and MLR was deterministic - "
                   "which is why SPLMSF and SPLMSFT never separated and MLR's PDR curve was too steep.  ANN, SVR "
                   "and RF are listed without a shadowing qualifier and stay deterministic; Table IV's RMSEs "
                   "are model accuracy and exclude psi."),
    dict(id="D3", status="determined (reconstruction choice)", topic="sf_max, the SF 11/12 packets, ADR window",
         paper_says="sf_max declared on Algorithm 1 line 2, value never printed; Section IV: 'the SF can take values "
                    "from 7 (SNR_limit = -7.5 dB) up to 12 (-20 dB)'; 'the NS collects 20 SNR samples and obtains "
                    "the maximum'.  Data descriptor 4.4: SF 7-10 only, 'according to the spectrum usage regulations'.",
         final_run="sf_max = 12 as the paper's Section IV states.  Every packet the simulation places on SF 11/12 is "
                   "EN3's (37 % of the test set, logged only at SF 10, mean SNR -12.5 dB); the data contain no SF 11/12 "
                   "(0.0 % of rows).  Window = the 20 samples BEFORE the packet, per device, over the test subset in "
                   "its SHUFFLED order: the only reading that reproduces the paper's Fig. 11 ADR curve (RMSE 1.4; "
                   "chronological history gives RMSE 20).  This is a reconstruction of what the paper's simulation did, "
                   "not an operational baseline: with chronological history the conventional ADR needs 4.8 dB "
                   "(test rows) or 4.4 dB (full campaign) for 99 % on the released data, not 11 - and the 10.7 dB of "
                   "the reconstructed data comes from the calibrated coupled outliers.  min_tp not identifiable."),
    # ---------------------------------------------------------------- assumed
    dict(id="A1", status="assumed", topic="Random seed", paper_says="'a fixed seed'; value not printed.",
         final_run="42 everywhere."),
    dict(id="A2", status="assumed", topic="Sensor-fault rows", paper_says="no rule given.",
         final_run="Drop rh <= 2 % (DHT22 stuck at exactly 1.0 in 4 090 rows).  No IQR/z trimming."),
    dict(id="A3", status="assumed", topic="Split mechanics", paper_says="caTools::sample.split, 80/20.",
         final_run="sklearn train_test_split(shuffle=True).  Equivalent in distribution, not row-for-row."),
    dict(id="A4", status="assumed", topic="Units in eq. (6)", paper_says="10*gamma*log10(d) + 20*log10(f).",
         final_run="d in km, f in Hz - the only units under which Table V's weights give the measured ~93 dB; "
                   "confirmed by gamma reproducing to 0.6 %."),
    dict(id="A5", status="assumed", topic="Definition of R^2",
         paper_says="'determination factor R2'.",
         final_run="Squared Pearson correlation.  Forced: Okumura-Hata has RMSE 39.7 dB on a 6.4 dB-sd "
                   "target (1-SSE/SST = -50) yet the paper prints 0.8064."),
    dict(id="A6", status="assumed", topic="Two-ray / Okumura-Hata parameterisation", paper_says="not printed.",
         final_run="Two-ray: 40log d - 20log ht - 20log hr.  Okumura-Hata: urban small/medium city, hb = EN "
                   "mast, hm = GW.  Six variants tried; none reproduces the paper's RMSE/R^2 pair."),
    dict(id="A7", status="assumed", topic="SPLMSF reference distance",
         paper_says="eq. (2) and III-A-1 say d0 = 1 m; Fig. 4 caption K = 84.2 needs d0 = 1 km and +K.",
         final_run="Fitted with d0 = 1 m; K reported at d0 = 1 km for comparison."),
    dict(id="A8", status="assumed", topic="ANN 'alpha'", paper_says="'regressor learning rate alpha ... 0.0001 "
         "(default value)'.", final_run="sklearn's L2 penalty `alpha` (whose default is 0.0001)."),
    dict(id="A9", status="assumed", topic="ANN solver", paper_says="not named; learning-rate schedules swept.",
         final_run="adam (default).  Under adam the schedule argument is inert, which the grid confirmed."),
    dict(id="A10", status="assumed", topic="SVR training size", paper_says="all 792 600 rows on a 16-node cluster.",
         final_run="Seeded 50 000-row subsample; a 10k-250k learning curve shows accuracy converged."),
    dict(id="A11", status="assumed", topic="SVR epsilon / target scaling", paper_says="only C, kernel, gamma swept.",
         final_run="epsilon = 0.1 (default); inputs scaled, target not."),
    dict(id="A12", status="assumed", topic="ANN cross-validation size", paper_says="5-fold on the training set.",
         final_run="100 000-row subsample for CV only; the final ANN is fitted on all 741 330 rows."),
    dict(id="A13", status="assumed", topic="Inputs and initial state of Algorithm 1", paper_says="line 1: SNR of the packet, noise_power; initial state not printed.",
         final_run="The SNR and noise floor Algorithm 1 sees are the SAME packet's measured values - legitimate for reconstructing the paper's retrospective figures, not available to a node before it transmits (review item 3; causal alternatives in outputs/provenance/validity/causal_features.csv).  current_tp = 20 dBm (the campaign setting) and current_sf = the row's logged SF for every "
                   "packet; per-node ltx/gtx/lrx/grx from the CSV (they differ between nodes: ltx is 1 or 11.75 dB).  "
                   "The stateful reading (current_tp / current_sf = the previous packet's outputs, per device) was "
                   "tested and refuted: the TP set-point does not depend on the starting TP, so state acts only "
                   "through the branch choice - a node below 20 dBm sees a negative margin and takes the SF-raise "
                   "branch - and airtime falls 60-110 points below the ADR at 80-95 % PDR (ToA RMSE 65-95 vs 19; "
                   "spending TP headroom before SF: 22-26).  Run statelessly the algorithm selects the "
                   "lowest SF whose set-point fits under 20 dBm, i.e. the minimum-airtime policy under its own margin.  "
                   "Evidence: outputs/provenance/adr_mechanism/stateful_fit.csv."),
    dict(id="A14", status="superseded by D4", topic="PDR decision rule (historical: the demodulation-threshold reading)",
         paper_says="'delivered if the actual RSSI was greater than the predicted RSSI'.",
         final_run="Received power at the chosen TP vs the demodulation threshold noise + SNR_limit(SF), "
                   "which reduces to (PL_true - PL_pred) < LM.  The literal form reduces to PL_pred > PL_true, "
                   "contains no LM, and gives a flat ~50 % line."),
    dict(id="D8", status="determined", topic="Noise floor for Algorithm 1",
         paper_says="'noise_power' input, undefined.  Data descriptor eqs. (3)-(4): ESP = RSSI + SNR - 10log10(1 + "
                    "10^(SNR/10)), Pn = RSSI - 10log10(1 + 10^(SNR/10)), so ESP - Pn = SNR.",
         final_run="rssi - snr, which makes line 5 read Me = SNR_est - SNR_limit - LM with SNR_est = SNR + (PL - "
                   "PL_hat) + (TP - 20): the same form as the ADR's Me = SNRmax - SNR_limit - LM.  The CSV's Pn "
                   "is the descriptor's eq. (4) exactly, but for a noise-dominated link RSSI ~ Pn, so Pn overstates "
                   "the margin by |SNR| (EN3: 12.8 dB on average); Algorithm 1 then cuts EN3's power by up to 15 dB "
                   "on a link 2.5 dB above its SF10 limit and the energy improvements reach +80 %.  "
                   "Evidence: text_audit.py, profile diagnostics in outputs/provenance/adr_mechanism/."),
    dict(id="A16", status="assumed", topic="ToA formula", paper_says="'can be found in [3]'.",
         final_run="Standard LoRa expression; reproduces the released `toa` column exactly (0 mismatches)."),
    dict(id="A17", status="assumed", topic="P_T in E = P_T x ToA", paper_says="'fitted a simple linear regression "
         "... R2 = 0.95'.", final_run="P_T = consumed power from the Table VII fit in mW.  Only this reading "
         "gives R^2 = 0.9458; a dBm-based fit gives 0.87."),
    dict(id="A18", status="superseded by D6", topic="Improvement operating point (historical: each scheme at its own crossing)", paper_says="'when PDR is 99 %'.",
         final_run="Each scheme at its own smallest LM reaching 99 %, vs the conventional ADR at its own."),
    dict(id="A19", status="superseded by D7", topic="SPLMSFT shadow-fading term (historical: fitted on SPLMSF residuals)", paper_says="'t-distributed shadow fading'; "
         "scale unstated; nu = 11.43 was fitted to MLR residuals.", final_run="nu fixed at 11.43, loc/scale "
         "MLE on the SPLMSF residuals; shadowing drawn per test row."),
]

SEED = 42
